default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webmon_development
  username: dev
  password: password
  host: 127.0.0.1


test:
  <<: *default
  database: webmon_test
  host: 127.0.0.1
  username: dev
  password: password

production:
  adapter: cockroachdb
  port: 26257
  database: timely
  username: password
  url: <%= ENV['DATABASE_URL'] %>
